//APLOAD PRODCUTS

export const UPLOAD_ALL_PRODUCTS = "UPLOAD_ALL_PRODUCTS";
export const UPLOAD_ALL_PRODUCTS_EXITO = "UPLOAD_ALL_PRODUCTS_EXITO";
export const UPLOAD_ALL_PRODUCTS_ERROR = "UPLOAD_ALL_PRODUCTS_ERROR";

//UPDATE PRODCUTS

export const UPDATE_ALL_PRODUCTS = "UPDATE_ALL_PRODUCTS";
export const UPDATE_ALL_PRODUCTS_EXITO = "UPDATE_ALL_PRODUCTS_EXITO";
export const UPDATE_ALL_PRODUCTS_ERROR = "UPDATE_ALL_PRODUCTS_ERROR";

//GET ALL PRODUCTS

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_EXITO = "GET_ALL_PRODUCTS_EXITO";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";
