const structuredTable = [
	["A1C/M", "FIAT", "500, TORO", 0],
	[
		"A2C/E",
		"PALIO, SIENA, IDEA, PUNTO, ARGO, STRADA, DOBLO, UNO NUEVO",
		0,
		"sin datos",
		"FIAT",
	],
	[
		"BE8/E",
		"AIRCROSS, C4 LOUNGE, BERLINGO, 206/207/208, 408, 308, 3008",
		0,
		"sin datos",
		"CITROEN - PEUGEOT",
	],
	[
		"HA/E",
		"ECOSPORT, FIESTA, FOCUS, MONDEO, S10, TRAILBLAZER, ONIX, PRISMA, GRAND SANTA FE",
		0,
		"sin datos",
		"FORD - CHEVROLET - HYUNDAI",
	],
	[
		"I3/E",
		"AGILE, CORSA, ASTRA, MERIVA, VECTRA,  CLIO, KANGOO, SYMBOL, SANDERO",
		0,
		"sin datos",
		"CHEVROLET -  RENAULT",
	],
	[
		"L2/E",
		"GOL G4/G5, SAVEIRO, UP, VOYAGE, TIGGO 5 ",
		0,
		"sin datos",
		"VOLSKWAGEN",
	],
	[
		"PP14/E",
		"AMAROK, TOUAREG, SPRINTER, Q7",
		0,
		"sin datos",
		"VOLSKWAGEN/AUDI",
	],
	[
		"ZA/E",
		"VENTO,BORA,GOLF,TIGUAN,PASAT,FOX,POLO,  A1,A3,A5 , FORD TERRITORY  ",
		0,
		"sin datos",
		"VOLSKWAGEN 5T - AUDI",
	],
	[
		"482/E",
		"HILUX,COROLLA,ETIOS,PRIUS,YARIS,SW4,RAV4",
		0,
		"sin datos",
		"TOYOTA (Aleación)",
	],
	["AC1/E", "TODOS", 0, "sin datos", "HONDA"],
	["BV2/D", "RENEGADE / PARTNER CHAPA", 0, "sin datos", "JEEP"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
	["xxxxx", "xxxxx", 0, "sin datos", "xxxxx"],
];

export const getStructureFarad = (table) => {
	console.log(table);
};
