export const guiaMarcas = {
	ESLINGAS: "KRAKEN",
	ALERONES: "BEPO",
	ALFOMBRAS: "ZIEL TECHNOLOGY",
	COBERTORES: "TRUCK LINER",
	DC: "DC",
	ZT: "ZIEL TECHNOLOGY",
	FARAD: "FARAD",
	BEPO: "BEPO",
	FLASHCOVER: "FLASHCOVER",
	KRAKEN: "KRAKEN",
};
export const headersColumProveedores = {
	FLASHCOVER: {
		codigoColum: 1,
		vehiculoColum: 2,
		masInfoColum: null,
		precioColum: 3,
		marcaColum: null,
	},
	ZT: {
		codigoColum: 1,
		vehiculoColum: 2,
		masInfoColum: 3,
		precioColum: 4,
		marcaColum: 0,
	},
	ALERONES: {
		codigoColum: 1,
		vehiculoColum: 2,
		masInfoColum: null,
		precioColum: 3,
		marcaColum: null,
	},
	COBERTORES: {
		codigoColum: 1,
		vehiculoColum: 2,
		masInfoColum: null,
		precioColum: 3,
		marcaColum: null,
	},
	KRAKEN: {
		codigoColum: 1,
		vehiculoColum: 2,
		masInfoColum: null,
		precioColum: 3,
		marcaColum: null,
	},
	BEPO: {
		codigoColum: 1,
		vehiculoColum: 2,
		masInfoColum: null,
		precioColum: 3,
		marcaColum: null,
	},
	ESLINGAS: {
		codigoColum: 1,
		vehiculoColum: 2,
		masInfoColum: null,
		precioColum: 3,
		marcaColum: null,
	},
	DC: {
		codigoColum: 1,
		vehiculoColum: 2,
		masInfoColum: null,
		precioColum: 3,
		marcaColum: null,
	},
};
