//APLOAD PRODCUTS

export const UPLOAD_ALL_PRODUCTS = "UPLOAD_ALL_PRODUCTS";
export const UPLOAD_ALL_PRODUCTS_EXITO = "UPLOAD_ALL_PRODUCTS_EXITO";
export const UPLOAD_ALL_PRODUCTS_ERROR = "UPLOAD_ALL_PRODUCTS_ERROR";

//UPDATE PRODCUTS

export const UPDATE_ALL_PRODUCTS = "UPDATE_ALL_PRODUCTS";
export const UPDATE_ALL_PRODUCTS_EXITO = "UPDATE_ALL_PRODUCTS_EXITO";
export const UPDATE_ALL_PRODUCTS_ERROR = "UPDATE_ALL_PRODUCTS_ERROR";

//UPDATE IMAGES SUBCATEGORIES

export const UPDATE_IMAGES_SUBCATEGORIES = "UPDATE_IMAGES_SUBCATEGORIES";
export const UPDATE_IMAGES_SUBCATEGORIES_EXITO =
	"UPDATE_IMAGES_SUBCATEGORIES_EXITO";
export const UPDATE_IMAGES_SUBCATEGORIES_ERROR =
	"UPDATE_IMAGES_SUBCATEGORIES_ERROR";

//GET ALL PRODUCTS

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_EXITO = "GET_ALL_PRODUCTS_EXITO";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";

//GET VALUES FROM ATTRIBUTE
export const GET_VALUES_ATTRIBUTES_SELECTS = "GET_VALUES_ATTRIBUTES_SELECTS";
export const GET_VALUES_ATTRIBUTES_SELECTS_EXITO =
	"GET_VALUES_ATTRIBUTES_SELECTS_EXITO";
export const GET_VALUES_ATTRIBUTES_SELECTS_ERROR =
	"GET_VALUES_ATTRIBUTES_SELECTS_ERROR";

//GET OPTINS SELECT TO UPDATE IMAGES

export const GET_OPTIONS_TO_UPDATE_IMAGES = "GET_OPTIONS_TO_UPDATE_IMAGES";
export const GET_OPTIONS_TO_UPDATE_IMAGES_EXITO =
	"GET_OPTIONS_TO_UPDATE_IMAGES_EXITO";
export const GET_OPTIONS_TO_UPDATE_IMAGES_ERROR =
	"GET_OPTIONS_TO_UPDATE_IMAGES_ERROR";

//GET IMAGES FROM SUBCATEGORIES

export const GET_IMAGES_SUBCATEGORIES = "GET_IMAGES_SUBCATEGORIES";
export const GET_IMAGES_SUBCATEGORIES_EXITO = "GET_IMAGES_SUBCATEGORIES_EXITO";
export const GET_IMAGES_SUBCATEGORIES_ERROR = "GET_IMAGES_SUBCATEGORIES_ERROR";
//SIGN UP USER

export const SIGN_UP_USER = "SIGN_UP_USER";
export const SIGN_UP_USER_EXITO = "SIGN_UP_USER_EXITO";
export const SIGN_UP_USER_ERROR = "SIGN_UP_USER_ERROR";

//SIGN IN USER

export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_IN_USER_EXITO = "SIGN_IN_USER_EXITO";
export const SIGN_IN_USER_ERROR = "SIGN_IN_USER_ERROR";

//SIGN OUT USER

export const SIGN_OUT_USER = "SIGN_OUT_USER";
export const SIGN_OUT_USER_EXITO = "SIGN_OUT_USER_EXITO";
export const SIGN_OUT_USER_ERROR = "SIGN_OUT_USER_ERROR";

//RESET REQUESTED VALUES

export const RESET_REQUESTED_VALUES = "RESET_REQUESTED_VALUES";
export const RESET_REQUESTED_VALUES_EXITO = "RESET_REQUESTED_VALUES_EXITO";
export const RESET_REQUESTED_VALUES_ERROR = "RESET_REQUESTED_VALUES_ERROR";
