//APLOAD PRODCUTS

export const UPLOAD_ALL_PRODUCTS = "UPLOAD_ALL_PRODUCTS";
export const UPLOAD_ALL_PRODUCTS_EXITO = "UPLOAD_ALL_PRODUCTS_EXITO";
export const UPLOAD_ALL_PRODUCTS_ERROR = "UPLOAD_ALL_PRODUCTS_ERROR";

//UPDATE PRODCUTS

export const UPDATE_ALL_PRODUCTS = "UPDATE_ALL_PRODUCTS";
export const UPDATE_ALL_PRODUCTS_EXITO = "UPDATE_ALL_PRODUCTS_EXITO";
export const UPDATE_ALL_PRODUCTS_ERROR = "UPDATE_ALL_PRODUCTS_ERROR";

//ADD NEW PRODUCT

export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const ADD_NEW_PRODUCT_EXITO = "ADD_NEW_PRODUCT_EXITO";
export const ADD_NEW_PRODUCT_ERROR = "ADD_NEW_PRODUCT_ERROR";

//DELETE ONE PRODUCT

export const DELETE_ONE_PRODUCT = "DELETE_ONE_PRODUCT";
export const DELETE_ONE_PRODUCT_EXITO = "DELETE_ONE_PRODUCT_EXITO";
export const DELETE_ONE_PRODUCT_ERROR = "DELETE_ONE_PRODUCT_ERROR";

//UPDATE IMAGES SUBCATEGORIES

export const UPDATE_IMAGES_PRODUCT = "UPDATE_IMAGES_PRODUCT";
export const UPDATE_IMAGES_PRODUCT_EXITO = "UPDATE_IMAGES_PRODUCT_EXITO";
export const UPDATE_IMAGES_PRODUCT_ERROR = "UPDATE_IMAGES_PRODUCT_ERROR";

//GET ALL PRODUCTS

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_EXITO = "GET_ALL_PRODUCTS_EXITO";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";

//GET VALUES FROM ATTRIBUTE
export const GET_VALUES_ATTRIBUTES_SELECTS = "GET_VALUES_ATTRIBUTES_SELECTS";
export const GET_VALUES_ATTRIBUTES_SELECTS_EXITO =
	"GET_VALUES_ATTRIBUTES_SELECTS_EXITO";
export const GET_VALUES_ATTRIBUTES_SELECTS_ERROR =
	"GET_VALUES_ATTRIBUTES_SELECTS_ERROR";

//GET OPTINS SELECT TO UPDATE IMAGES

export const GET_OPTIONS_TO_UPDATE_IMAGES = "GET_OPTIONS_TO_UPDATE_IMAGES";
export const GET_OPTIONS_TO_UPDATE_IMAGES_EXITO =
	"GET_OPTIONS_TO_UPDATE_IMAGES_EXITO";
export const GET_OPTIONS_TO_UPDATE_IMAGES_ERROR =
	"GET_OPTIONS_TO_UPDATE_IMAGES_ERROR";

//GET IMAGES FROM SUBCATEGORIES

export const GET_IMAGES_SUBCATEGORIES = "GET_IMAGES_SUBCATEGORIES";
export const GET_IMAGES_SUBCATEGORIES_EXITO = "GET_IMAGES_SUBCATEGORIES_EXITO";
export const GET_IMAGES_SUBCATEGORIES_ERROR = "GET_IMAGES_SUBCATEGORIES_ERROR";
//SIGN UP USER

export const SIGN_UP_USER = "SIGN_UP_USER";
export const SIGN_UP_USER_EXITO = "SIGN_UP_USER_EXITO";
export const SIGN_UP_USER_ERROR = "SIGN_UP_USER_ERROR";

//SIGN IN USER

export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_IN_USER_EXITO = "SIGN_IN_USER_EXITO";
export const SIGN_IN_USER_ERROR = "SIGN_IN_USER_ERROR";

//SIGN OUT USER

export const SIGN_OUT_USER = "SIGN_OUT_USER";
export const SIGN_OUT_USER_EXITO = "SIGN_OUT_USER_EXITO";
export const SIGN_OUT_USER_ERROR = "SIGN_OUT_USER_ERROR";

//RESET REQUESTED VALUES

export const RESET_REQUESTED_VALUES = "RESET_REQUESTED_VALUES";
export const RESET_REQUESTED_VALUES_EXITO = "RESET_REQUESTED_VALUES_EXITO";
export const RESET_REQUESTED_VALUES_ERROR = "RESET_REQUESTED_VALUES_ERROR";

//RESET MSGS RESPONSES

export const RESET_RESPONSE_MSGS = "RESET_RESPONSE_MSGS";
export const RESET_RESPONSE_MSGS_EXITO = "RESET_RESPONSE_MSGS_EXITO";
export const RESET_RESPONSE_MSGS_ERROR = "RESET_RESPONSE_MSGS_ERROR";
