//APLOAD PRODCUTS

export const UPLOAD_ALL_PRODUCTS = "UPLOAD_ALL_PRODUCTS";
export const UPLOAD_ALL_PRODUCTS_EXITO = "UPLOAD_ALL_PRODUCTS_EXITO";
export const UPLOAD_ALL_PRODUCTS_ERROR = "UPLOAD_ALL_PRODUCTS_ERROR";

//UPDATE PRODCUTS

export const UPDATE_ALL_PRODUCTS = "UPDATE_ALL_PRODUCTS";
export const UPDATE_ALL_PRODUCTS_EXITO = "UPDATE_ALL_PRODUCTS_EXITO";
export const UPDATE_ALL_PRODUCTS_ERROR = "UPDATE_ALL_PRODUCTS_ERROR";

//ADD NEW PRODUCT

export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const ADD_NEW_PRODUCT_EXITO = "ADD_NEW_PRODUCT_EXITO";
export const ADD_NEW_PRODUCT_ERROR = "ADD_NEW_PRODUCT_ERROR";

//DELETE ONE PRODUCT

export const DELETE_ONE_PRODUCT = "DELETE_ONE_PRODUCT";
export const DELETE_ONE_PRODUCT_EXITO = "DELETE_ONE_PRODUCT_EXITO";
export const DELETE_ONE_PRODUCT_ERROR = "DELETE_ONE_PRODUCT_ERROR";

//UPDATE IMAGES SUBCATEGORIES

export const UPDATE_IMAGES_PRODUCT = "UPDATE_IMAGES_PRODUCT";
export const UPDATE_IMAGES_PRODUCT_EXITO = "UPDATE_IMAGES_PRODUCT_EXITO";
export const UPDATE_IMAGES_PRODUCT_ERROR = "UPDATE_IMAGES_PRODUCT_ERROR";

//GET ALL PRODUCTS

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_EXITO = "GET_ALL_PRODUCTS_EXITO";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";

//GET VALUES FROM ATTRIBUTE
export const GET_VALUES_ATTRIBUTES_SELECTS = "GET_VALUES_ATTRIBUTES_SELECTS";
export const GET_VALUES_ATTRIBUTES_SELECTS_EXITO =
	"GET_VALUES_ATTRIBUTES_SELECTS_EXITO";
export const GET_VALUES_ATTRIBUTES_SELECTS_ERROR =
	"GET_VALUES_ATTRIBUTES_SELECTS_ERROR";

//GET OPTINS SELECT TO UPDATE IMAGES

export const GET_OPTIONS_TO_UPDATE_IMAGES = "GET_OPTIONS_TO_UPDATE_IMAGES";
export const GET_OPTIONS_TO_UPDATE_IMAGES_EXITO =
	"GET_OPTIONS_TO_UPDATE_IMAGES_EXITO";
export const GET_OPTIONS_TO_UPDATE_IMAGES_ERROR =
	"GET_OPTIONS_TO_UPDATE_IMAGES_ERROR";

//GET IMAGES FROM SUBCATEGORIES

export const GET_IMAGES_SUBCATEGORIES = "GET_IMAGES_SUBCATEGORIES";
export const GET_IMAGES_SUBCATEGORIES_EXITO = "GET_IMAGES_SUBCATEGORIES_EXITO";
export const GET_IMAGES_SUBCATEGORIES_ERROR = "GET_IMAGES_SUBCATEGORIES_ERROR";
//SIGN UP USER

export const SIGN_UP_USER = "SIGN_UP_USER";
export const SIGN_UP_USER_EXITO = "SIGN_UP_USER_EXITO";
export const SIGN_UP_USER_ERROR = "SIGN_UP_USER_ERROR";

//SIGN IN USER

export const SIGN_IN_ADMIN = "SIGN_IN_ADMIN";
export const SIGN_IN_ADMIN_EXITO = "SIGN_IN_ADMIN_EXITO";
export const SIGN_IN_ADMIN_ERROR = "SIGN_IN_ADMIN_ERROR";

//SIGN OUT USER

export const SIGN_OUT_USER = "SIGN_OUT_USER";
export const SIGN_OUT_USER_EXITO = "SIGN_OUT_USER_EXITO";
export const SIGN_OUT_USER_ERROR = "SIGN_OUT_USER_ERROR";

//RESET IMAGES RECEIVED STORE

export const RESET_IMAGES_RECEIVED_STORE = "RESET_IMAGES_RECEIVED_STORE";
export const RESET_IMAGES_RECEIVED_STORE_EXITO =
	"RESET_IMAGES_RECEIVED_STORE_EXITO";
export const RESET_IMAGES_RECEIVED_STORE_ERROR =
	"RESET_IMAGES_RECEIVED_STORE_ERROR";

//RESET OPTIONS SELECT RECEIVED STORE

export const RESET_OPTIONS_RECEIVED_STORE = "RESET_OPTIONS_RECEIVED_STORE";
export const RESET_OPTIONS_RECEIVED_STORE_EXITO =
	"RESET_OPTIONS_RECEIVED_STORE_EXITO";
export const RESET_OPTIONS_RECEIVED_STORE_ERROR =
	"RESET_OPTIONS_RECEIVED_STORE_ERROR";

//RESET MSGS RESPONSES

export const RESET_RESPONSE_MSGS = "RESET_RESPONSE_MSGS";
export const RESET_RESPONSE_MSGS_EXITO = "RESET_RESPONSE_MSGS_EXITO";
export const RESET_RESPONSE_MSGS_ERROR = "RESET_RESPONSE_MSGS_ERROR";

//ADD PRODUCT TO CART

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const ADD_PRODUCT_TO_CART_EXITO = "ADD_PRODUCT_TO_CART_EXITO";
export const ADD_PRODUCT_TO_CART_ERROR = "ADD_PRODUCT_TO_CART_ERROR";

//UPDATE AMOUNT PRODUCT TO CART

export const UPDATE_PRODUCT_AMOUNT_CART = "UPDATE_PRODUCT_AMOUNT_CART";
export const UPDATE_PRODUCT_AMOUNT_CART_EXITO =
	"UPDATE_PRODUCT_AMOUNT_CART_EXITO";
export const UPDATE_PRODUCT_AMOUNT_CART_ERROR =
	"UPDATE_PRODUCT_AMOUNT_CART_ERROR";

//RESET_RESPONSE_MSGS

export const RESET_RESPONSE_MSGS_CART = "RESET_RESPONSE_MSGS_CART";
export const RESET_RESPONSE_MSGS_CART_EXITO = "RESET_RESPONSE_MSGS_CART_EXITO";
export const RESET_RESPONSE_MSGS_CART_ERROR = "RESET_RESPONSE_MSGS_CART_ERROR";

//DELETE PRODUCT TO CART

export const DELETE_PRODUCT_TO_CART = "DELETE_PRODUCT_TO_CART";
export const DELETE_PRODUCT_TO_CART_EXITO = "DELETE_PRODUCT_TO_CART_EXITO";
export const DELETE_PRODUCT_TO_CART_ERROR = "DELETE_PRODUCT_TO_CART_ERROR";

//ADD PRODUCT TO NEWS

export const ADD_PRODUCT_TO_NEWS = "ADD_PRODUCT_TO_NEWS";
export const ADD_PRODUCT_TO_NEWS_EXITO = "ADD_PRODUCT_TO_NEWS_EXITO";
export const ADD_PRODUCT_TO_NEWS_ERROR = "ADD_PRODUCT_TO_NEWS_ERROR";

//GET ALL NEWS

export const GET_ALL_NEWS = "GET_ALL_NEWS";
export const GET_ALL_NEWS_EXITO = "GET_ALL_NEWS_EXITO";
export const GET_ALL_NEWS_ERROR = "GET_ALL_NEWS_ERROR";

//DELETE ONE NEWS

export const DELETE_NEWS = "DELETE_NEWS";
export const DELETE_NEWS_EXITO = "DELETE_NEWS_EXITO";
export const DELETE_NEWS_ERROR = "DELETE_NEWS_ERROR";

//ADD NEW ACCESSORIE IMAGE

export const ADD_NEW_ACCESSORIE_IMAGE = "ADD_NEW_ACCESSORIE_IMAGE";
export const ADD_NEW_ACCESSORIE_IMAGE_EXITO = "ADD_NEW_ACCESSORIE_IMAGE_EXITO";
export const ADD_NEW_ACCESSORIE_IMAGE_ERROR = "ADD_NEW_ACCESSORIE_IMAGE_ERROR";

//GET ACCESSORIE IMAGES

export const GET_ACCESSORIE_IMAGES = "GET_ACCESSORIE_IMAGES";
export const GET_ACCESSORIE_IMAGES_EXITO = "GET_ACCESSORIE_IMAGES_EXITO";
export const GET_ACCESSORIE_IMAGES_ERROR = "GET_ACCESSORIE_IMAGES_ERROR";

//DELETE ACCESSORIE IMAGES

export const DELETE_ACCESSORIE_IMAGES = "DELETE_ACCESSORIE_IMAGES";
export const DELETE_ACCESSORIE_IMAGES_EXITO = "DELETE_ACCESSORIE_IMAGES_EXITO";
export const DELETE_ACCESSORIE_IMAGES_ERROR = "DELETE_ACCESSORIE_IMAGES_ERROR";

//DELETE ACCESSORIE IMAGES

export const GET_ACCESSORIE_CATEGORIES = "GET_ACCESSORIE_CATEGORIES";
export const GET_ACCESSORIE_CATEGORIES_EXITO =
	"GET_ACCESSORIE_CATEGORIES_EXITO";
export const GET_ACCESSORIE_CATEGORIES_ERROR =
	"GET_ACCESSORIE_CATEGORIES_ERROR";

//RESET ACCESSORIE IMAGES STATE

export const RESET_ACCESSORIE_STATE = "RESET_ACCESSORIE_STATE";
export const RESET_ACCESSORIE_STATE_EXITO = "RESET_ACCESSORIE_STATE_EXITO";
export const RESET_ACCESSORIE_STATE_ERROR = "RESET_ACCESSORIE_STATE_ERROR";
//ADD NEW USER

export const ADD_NEW_USER = "ADD_NEW_USER";
export const ADD_NEW_USER_EXITO = "ADD_NEW_USER_EXITO";
export const ADD_NEW_USER_ERROR = "ADD_NEW_USER_ERROR";

//SIGN IN USER

export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_IN_USER_EXITO = "SIGN_IN_USER_EXITO";
export const SIGN_IN_USER_ERROR = "SIGN_IN_USER_ERROR";

//LOG OUT USER

export const LOG_OUT_USER = "LOG_OUT_USER";
export const LOG_OUT_USER_EXITO = "LOG_OUT_USER_EXITO";
export const LOG_OUT_USER_ERROR = "LOG_OUT_USER_ERROR";
